language: python
python:
  - "3.6"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE demo_texada;'
  - mysql -e "GRANT ALL PRIVILEGES ON demo_texada.* to 'demoer'@'localhost' identified by 'showmesomething';"
  - mysql demo_texada < $TRAVIS_BUILD_DIR/initial_data_quickstart.sql -u demoer -pshowmesomething
install:
  - pip install -r requirements.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - python manage.py makemigrations api
  - python manage.py migrate api
  - coverage run --source=. -m unittest
  - coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
